apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-directory
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
          #    directory:
          #      exclude: 'service.yml'
          #      include: '{serviceaccount.yml,service.yml}'
          #      recurse: true
    path: 1-application/directory
    repoURL: https://github.com/sinamna/gitops-learning.git
    targetRevision: main
