apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-helm-nginx
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: test-project
  source:
    helm:
        releaseName: application-from-helm
        valueFiles:
          - custom-values.yaml
        valuesObject:
          replicaCount: 1
    path: 1-application/helm/nginx
    repoURL: https://github.com/sinamna/gitops-learning.git
    targetRevision: main
