apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-project
  namespace: argocd
spec:
  description: Test project for test-user
  sourceRepos:
    - '*'  # Or your Git repo
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  roles:
    - name: test-role
      description: Full access to applications in test-project
      policies:
        - p, proj:test-project:test-role, applications, get, test-project/*, allow
        - p, proj:test-project:test-role, applications, create, test-project/*, allow
        - p, proj:test-project:test-role, applications, update, test-project/*, allow
        - p, proj:test-project:test-role, applications, delete, test-project/*, allow
      # groups:
      #   - test-user
