apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-guestbook
  namespace: argocd
spec:
  destination:
    namespace: child-guestbook
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: app/guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}