apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-nginx
  namespace: argocd
spec:
  destination:
    namespace: child-nginx
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/nginx
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}